name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Get Vercel Preview URL
        id: get_preview_url
        run: |
          # Use the Vercel API to fetch the preview URL
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" "https://api.vercel.com/v5/now/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&filter=ready")
          BASE_URL=$(echo $response | jq -r '.deployments[0].url')
          BASE_URL="https://$BASE_URL"
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV
          echo "Preview URL is: $BASE_URL"
      - name: Run Playwright tests
        run: npx playwright test --timeout=120000
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
